--Tabela anime não normalizada com os tipos de dados corretos
DROP TABLE IF EXISTS "Projeto-Anime".anime;
CREATE TABLE "Projeto-Anime"."anime" (
	mal_id int NULL,
	"name" text NULL,
	score decimal(3,2) NULL,
	genres text NULL,
	english_name text NULL,
	japanese_name text NULL,
	"type" varchar(50) NULL,
	episodes int NULL,
	aired varchar(50) NULL,
	premiered text NULL,
	producers text NULL,
	licensors text NULL,
	studios text NULL,
	"source" varchar(50) NULL,
	duration varchar(50) NULL,
	rating varchar(50) NULL,
	ranked int NULL,
	popularity int NULL,
	members int NULL,
	favorites int NULL,
	watching int NULL,
	completed int NULL,
	"on-hold" int NULL,
	dropped int NULL,
	plan_to_watch int NULL,
	"score-10" int NULL,
	"score-9" int NULL,
	"score-8" int NULL,
	"score-7" int NULL,
	"score-6" int NULL,
	"score-5" int NULL,
	"score-4" int NULL,
	"score-3" int NULL,
	"score-2" int NULL,
	"score-1" int NULL
);

-- Transferência de dados entre as tabelas
INSERT INTO "Projeto-Anime".anime (
    mal_id,
    "name",
    score,
    genres,
    english_name,
    japanese_name,
    "type",
    episodes,
    aired,
    premiered,
    producers,
    licensors,
    studios,
    "source",
    duration,
    rating,
    ranked,
    popularity,
    members,
    favorites,
    watching,
    completed,
    "on-hold",
    dropped,
    plan_to_watch,
    "score-10",
    "score-9",
    "score-8",
    "score-7",
    "score-6",
    "score-5",
    "score-4",
    "score-3",
    "score-2",
    "score-1"
)
SELECT
    CASE WHEN mal_id ~ '^[0-9]+$' THEN mal_id::INT ELSE NULL END,
    NULLIF("name", ''),
    CASE WHEN score ~ '^[0-9]+(\.[0-9]+)?$' THEN score::DECIMAL(3,2) ELSE NULL END,
    NULLIF(genres, ''),
    NULLIF(english_name, ''),
    NULLIF(japanese_name, ''),
    NULLIF("type", ''),
    CASE when episodes ~ '^[0-9]+$' then episodes::INT ELSE NULL END,
    NULLIF(aired, ''),
    NULLIF(premiered, ''),
    NULLIF(producers, ''),
    NULLIF(licensors, ''),
    NULLIF(studios, ''),
    NULLIF("source", ''),
    NULLIF(duration, ''),
    NULLIF(rating, ''),
    CASE WHEN ranked ~ '^[0-9]+(\.[0-9]+)?$' then cast(REPLACE(ranked, '.0','' ) as INT)  ELSE NULL END,
    CASE WHEN popularity ~ '^[0-9]+$' THEN popularity::INT ELSE NULL END,
    CASE WHEN members ~ '^[0-9]+$' THEN members::INT ELSE NULL END,
    CASE WHEN favorites ~ '^[0-9]+$' THEN favorites::INT ELSE NULL END,
    CASE WHEN watching ~ '^[0-9]+$' THEN watching::INT ELSE NULL END,
    CASE WHEN completed ~ '^[0-9]+$' THEN completed::INT ELSE NULL END,
    CASE WHEN "on-hold" ~ '^[0-9]+$' THEN "on-hold"::INT ELSE NULL END,
    CASE WHEN dropped ~ '^[0-9]+$' THEN dropped::INT ELSE NULL END,
    CASE WHEN plan_to_watch ~ '^[0-9]+$' THEN plan_to_watch::INT ELSE NULL END,
    CASE WHEN "score-10" ~ '^[0-9]+(\.[0-9]+)?$' THEN cast(REPLACE("score-10", '.0','') as INT) ELSE NULL END, -- A conversão direta para INT (ou INTEGER) descartará o '.0'
    CASE WHEN "score-9"  ~ '^[0-9]+(\.[0-9]+)?$' THEN cast(REPLACE("score-9",'.0','') as INT) ELSE NULL END,
    CASE WHEN "score-8"  ~ '^[0-9]+(\.[0-9]+)?$' THEN cast(REPLACE("score-8",'.0','') as INT) ELSE NULL END,
    CASE WHEN "score-7"  ~ '^[0-9]+(\.[0-9]+)?$' THEN cast(REPLACE("score-7",'.0','') as INT) ELSE NULL END,
    CASE WHEN "score-6"  ~ '^[0-9]+(\.[0-9]+)?$' THEN cast(REPLACE("score-6",'.0','') as INT) ELSE NULL END,
    CASE WHEN "score-5"  ~ '^[0-9]+(\.[0-9]+)?$' THEN cast(REPLACE("score-5",'.0','') as INT) ELSE NULL END,
    CASE WHEN "score-4"  ~ '^[0-9]+(\.[0-9]+)?$' THEN cast(REPLACE("score-4",'.0','') as INT) ELSE NULL END,
    CASE WHEN "score-3"  ~ '^[0-9]+(\.[0-9]+)?$' THEN cast(REPLACE("score-3",'.0','') as INT) ELSE NULL END,
    CASE WHEN "score-2"  ~ '^[0-9]+(\.[0-9]+)?$' THEN cast(REPLACE("score-2",'.0','') as INT) ELSE NULL END,
    CASE WHEN "score-1"  ~ '^[0-9]+(\.[0-9]+)?$' THEN cast(REPLACE("score-1",'.0','') as INT) ELSE NULL END
FROM anime_temp;
